# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    # Triggers on every tag starting with v
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install libfdt-dev and cmake
        run: sudo apt install libfdt-dev cmake

      - name: Run builder script
        run: mkdir -m 0700 $HOME/.gnupg ; bash build_installer.sh

#      - name: Store created images
#        uses: actions/upload-artifact@v2
#        with:
#          name: images
#          path: |
#            *.itb

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openwrt*-mediatek-mt7622-linksys_e8450-ubi-squashfs-sysupgrade.itb
            openwrt*-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery.itb
            openwrt*-mediatek-mt7622-linksys_e8450-ubi-initramfs-recovery-installer.itb
